name: ci

on:
  push:
    branches:
      - main
      - v1
  pull_request:
    branches:
      - main
      - v1

permissions:
  id-token: write

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [18, 20]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: "pnpm"
      - uses: oven-sh/setup-bun@v2
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.node == 20 }}
        with:
          bun-version: latest
      - run: pnpm install
      - run: pnpm lint
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.node == 20 }}
      - run: pnpm build
      - run: pnpm vitest run --coverage
      - run: pnpm test:register
      - run: pnpm test:bun --coverage
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.node == 20 }}
      - name: nightly release
        if: |
          github.event_name == 'push' &&
          !contains(github.event.head_commit.message, '[skip-release]') &&
          !startsWith(github.event.head_commit.message, 'docs')
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc &&
          pnpm changelogen --canary nightly --publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
