name: ci

on:
  push:
    branches:
      - main
      - v1
  pull_request:
    branches:
      - main
      - v1

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [22]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: "pnpm"
      - uses: oven-sh/setup-bun@v2
        if: ${{ matrix.os != 'windows-latest' && matrix.node == 22 }}
        with:
          bun-version: latest
      - run: pnpm install
      - run: pnpm lint
        if: ${{ matrix.os != 'windows-latest' && matrix.node == 22 }}
      - run: pnpm build
      - run: pnpm vitest run --coverage
      - run: pnpm test:bun --coverage
        if: ${{ matrix.os != 'windows-latest' && matrix.node == 22 }}
      # - name: Coverage
      #   uses: codecov/codecov-action@v1
