name: Publish with pkg.pr.new

on:
  pull_request:
  push:
    branches:
      - "**"
    tags:
      - "!**"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - run: pnpx pkg-pr-new publish --compact
